/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBillingRouteImport } from './routes/account.billing'
import { Route as AccountPrivacyRouteImport } from './routes/account.privacy'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai-status'
import { Route as ApiEditArtworkRouteImport } from './routes/api/edit-artwork'
import { Route as ApiPhotoSearchRouteImport } from './routes/api/photo-search'
import { Route as ApiPrintHandoffRouteImport } from './routes/api/print-handoff'
import { Route as ApiWriteMessageRouteImport } from './routes/api/write-message'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateCardRouteImport } from './routes/create.card'
import { Route as CreatePrintRouteImport } from './routes/create.print'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as PrivacyIndexRouteImport } from './routes/privacy.index'
import { Route as PrivacyRequestRouteImport } from './routes/privacy.request'
import { Route as SharePublicTokenRouteImport } from './routes/share.$publicToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPrivacyRoute = AccountPrivacyRouteImport.update({
  id: '/account/privacy',
  path: '/account/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai-status',
  path: '/api/ai-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditArtworkRoute = ApiEditArtworkRouteImport.update({
  id: '/api/edit-artwork',
  path: '/api/edit-artwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoSearchRoute = ApiPhotoSearchRouteImport.update({
  id: '/api/photo-search',
  path: '/api/photo-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrintHandoffRoute = ApiPrintHandoffRouteImport.update({
  id: '/api/print-handoff',
  path: '/api/print-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWriteMessageRoute = ApiWriteMessageRouteImport.update({
  id: '/api/write-message',
  path: '/api/write-message',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCardRoute = CreateCardRouteImport.update({
  id: '/create/card',
  path: '/create/card',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePrintRoute = CreatePrintRouteImport.update({
  id: '/create/print',
  path: '/create/print',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRequestRoute = PrivacyRequestRouteImport.update({
  id: '/privacy/request',
  path: '/privacy/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePublicTokenRoute = SharePublicTokenRouteImport.update({
  id: '/share/$publicToken',
  path: '/share/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRoute
  '/people': typeof PeopleRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/edit-artwork': typeof ApiEditArtworkRoute
  '/api/photo-search': typeof ApiPhotoSearchRoute
  '/api/print-handoff': typeof ApiPrintHandoffRoute
  '/api/write-message': typeof ApiWriteMessageRoute
  '/create/card': typeof CreateCardRoute
  '/create/print': typeof CreatePrintRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/privacy/request': typeof PrivacyRequestRoute
  '/share/$publicToken': typeof SharePublicTokenRoute
  '/account/': typeof AccountIndexRoute
  '/create/': typeof CreateIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRoute
  '/people': typeof PeopleRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/edit-artwork': typeof ApiEditArtworkRoute
  '/api/photo-search': typeof ApiPhotoSearchRoute
  '/api/print-handoff': typeof ApiPrintHandoffRoute
  '/api/write-message': typeof ApiWriteMessageRoute
  '/create/card': typeof CreateCardRoute
  '/create/print': typeof CreatePrintRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/privacy/request': typeof PrivacyRequestRoute
  '/share/$publicToken': typeof SharePublicTokenRoute
  '/account': typeof AccountIndexRoute
  '/create': typeof CreateIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/privacy': typeof PrivacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/library': typeof LibraryRoute
  '/people': typeof PeopleRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/ai-status': typeof ApiAiStatusRoute
  '/api/edit-artwork': typeof ApiEditArtworkRoute
  '/api/photo-search': typeof ApiPhotoSearchRoute
  '/api/print-handoff': typeof ApiPrintHandoffRoute
  '/api/write-message': typeof ApiWriteMessageRoute
  '/create/card': typeof CreateCardRoute
  '/create/print': typeof CreatePrintRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/privacy/request': typeof PrivacyRequestRoute
  '/share/$publicToken': typeof SharePublicTokenRoute
  '/account/': typeof AccountIndexRoute
  '/create/': typeof CreateIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/gallery'
    | '/help'
    | '/how-it-works'
    | '/library'
    | '/people'
    | '/pricing'
    | '/products'
    | '/terms'
    | '/account/billing'
    | '/account/privacy'
    | '/admin/content'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/support'
    | '/api/ai-status'
    | '/api/edit-artwork'
    | '/api/photo-search'
    | '/api/print-handoff'
    | '/api/write-message'
    | '/create/card'
    | '/create/print'
    | '/orders/$orderId'
    | '/privacy/request'
    | '/share/$publicToken'
    | '/account/'
    | '/create/'
    | '/orders/'
    | '/privacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/gallery'
    | '/help'
    | '/how-it-works'
    | '/library'
    | '/people'
    | '/pricing'
    | '/products'
    | '/terms'
    | '/account/billing'
    | '/account/privacy'
    | '/admin/content'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/support'
    | '/api/ai-status'
    | '/api/edit-artwork'
    | '/api/photo-search'
    | '/api/print-handoff'
    | '/api/write-message'
    | '/create/card'
    | '/create/print'
    | '/orders/$orderId'
    | '/privacy/request'
    | '/share/$publicToken'
    | '/account'
    | '/create'
    | '/orders'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/gallery'
    | '/help'
    | '/how-it-works'
    | '/library'
    | '/people'
    | '/pricing'
    | '/products'
    | '/terms'
    | '/account/billing'
    | '/account/privacy'
    | '/admin/content'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/support'
    | '/api/ai-status'
    | '/api/edit-artwork'
    | '/api/photo-search'
    | '/api/print-handoff'
    | '/api/write-message'
    | '/create/card'
    | '/create/print'
    | '/orders/$orderId'
    | '/privacy/request'
    | '/share/$publicToken'
    | '/account/'
    | '/create/'
    | '/orders/'
    | '/privacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  GalleryRoute: typeof GalleryRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LibraryRoute: typeof LibraryRoute
  PeopleRoute: typeof PeopleRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  TermsRoute: typeof TermsRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountPrivacyRoute: typeof AccountPrivacyRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiEditArtworkRoute: typeof ApiEditArtworkRoute
  ApiPhotoSearchRoute: typeof ApiPhotoSearchRoute
  ApiPrintHandoffRoute: typeof ApiPrintHandoffRoute
  ApiWriteMessageRoute: typeof ApiWriteMessageRoute
  CreateCardRoute: typeof CreateCardRoute
  CreatePrintRoute: typeof CreatePrintRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PrivacyRequestRoute: typeof PrivacyRequestRoute
  SharePublicTokenRoute: typeof SharePublicTokenRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/privacy': {
      id: '/account/privacy'
      path: '/account/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AccountPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-status': {
      id: '/api/ai-status'
      path: '/api/ai-status'
      fullPath: '/api/ai-status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-artwork': {
      id: '/api/edit-artwork'
      path: '/api/edit-artwork'
      fullPath: '/api/edit-artwork'
      preLoaderRoute: typeof ApiEditArtworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo-search': {
      id: '/api/photo-search'
      path: '/api/photo-search'
      fullPath: '/api/photo-search'
      preLoaderRoute: typeof ApiPhotoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/print-handoff': {
      id: '/api/print-handoff'
      path: '/api/print-handoff'
      fullPath: '/api/print-handoff'
      preLoaderRoute: typeof ApiPrintHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/write-message': {
      id: '/api/write-message'
      path: '/api/write-message'
      fullPath: '/api/write-message'
      preLoaderRoute: typeof ApiWriteMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/card': {
      id: '/create/card'
      path: '/create/card'
      fullPath: '/create/card'
      preLoaderRoute: typeof CreateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/print': {
      id: '/create/print'
      path: '/create/print'
      fullPath: '/create/print'
      preLoaderRoute: typeof CreatePrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/request': {
      id: '/privacy/request'
      path: '/privacy/request'
      fullPath: '/privacy/request'
      preLoaderRoute: typeof PrivacyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$publicToken': {
      id: '/share/$publicToken'
      path: '/share/$publicToken'
      fullPath: '/share/$publicToken'
      preLoaderRoute: typeof SharePublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  GalleryRoute: GalleryRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LibraryRoute: LibraryRoute,
  PeopleRoute: PeopleRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  TermsRoute: TermsRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountPrivacyRoute: AccountPrivacyRoute,
  AdminContentRoute: AdminContentRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSupportRoute: AdminSupportRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiEditArtworkRoute: ApiEditArtworkRoute,
  ApiPhotoSearchRoute: ApiPhotoSearchRoute,
  ApiPrintHandoffRoute: ApiPrintHandoffRoute,
  ApiWriteMessageRoute: ApiWriteMessageRoute,
  CreateCardRoute: CreateCardRoute,
  CreatePrintRoute: CreatePrintRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PrivacyRequestRoute: PrivacyRequestRoute,
  SharePublicTokenRoute: SharePublicTokenRoute,
  AccountIndexRoute: AccountIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
